### PR TITLE
Add example for hyper 0.12

### PR DESCRIPTION
**Pull request by nickelc**

### CODE REVIEW

**Comment by cetra3** [comment]
Great PR! Is it possible to create an example that doesn't depend on `httpbin` ?

**Comment by nickelc** [comment]
what's the problem with using httpbin?

**Comment by cetra3** [comment]
No real problem, but it would be nice if you didn't need to rely on an external service to ensure the example runs.

**Comment by nickelc** [comment]
done

**Comment by cetra3** [comment]
Good stuff

**Pull request merged**
