### PR TITLE
Use pin-project-lite instead of pin-project

### PR DESCRIPTION
**Pull request by nwtgck**
Thank you so much for the great library! The API of `mpart-async` is exactly what I want.

This PR is a just refactoring. Using pin-project-lite should be faster in build time.

### CODE REVIEW

**Comment by cetra3** [comment]
Thanks for the PR!

**Comment by nwtgck** [comment]
@cetra3 
Thank you so much for merging! Could you release new version? 
mpart-async is only one crate using pin-project in my project.

**Comment by cetra3** [comment]
Apologies for the wait @nwtgck I've published version `0.6.0` with the pin-project-lite dep

**Comment by nwtgck** [comment]
Thank you so much!

**Pull request merged**
